[tool.poetry]
name = "htcli"
version = "0.1.0"
description = "Hypertensor CLI tool"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
packages = [{include = "htcli"}]

[tool.poetry.dependencies]
python = "^3.8"
typer = {extras = ["all"], version = "^0.9.0"}
substrate-interface = "^1.7.5"
mnemonic = "^0.20"
rich = "^13.7.0"  # For better terminal output
click = "^8.1.7"  # Required by typer
cryptography = "^41.0.0"  # Required for key operations
protobuf = "^4.25.1"  # Required by substrate-interface
six = "^1.16.0"  # Required by substrate-interface
base58 = "^2.1.1"  # Required for SS58 address encoding
scalecodec = "^1.0.0"  # Required by substrate-interface

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.7.0"
isort = "^5.12.0"
mypy = "^1.5.1"
flake8 = "^6.1.0"
pytest-cov = "^4.1.0"  # For test coverage

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py38']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --cov=htcli"
