[project]
name = "htcli"
version = "0.1.0"
description = "CLI to interact with Hypertensor"
authors = [{ name = "ultrashiny", email = "vasyl.123.000@gmail.com" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "typer[all] (>=0.15.3,<0.16.0)",
    "click (==8.0.4)",
]

[project.urls]
repository = "https://github.com/shiftlayer-llc/htcli"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
htcli = "htcli.main:app"
